# This file is meant for locally running the components with dev servers.

volumes:
  db-data:

services:
  backend:
    image: node:24.15-alpine
    working_dir: /backend
    depends_on:
      db:
        condition: service_started
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      APPLICATION_PORT: 3000
      AWS_SES_KEY_ID:
      AWS_SES_KEY_VALUE:
      AWS_SES_REGION:
      CERT_SELECTION:
      EMAIL_SOURCE:
      EMAIL_RETURN_PATH:
      ENABLE_SETUP_ENDPOINTS: yes
      ENTRA_ADMIN_ROLE:
      ENTRA_APP_KEY_DISCOVERY_URL:
      DB_HOST: db # In case a local postgres exists and env variable is already set.
      DB_NAME:
      DB_PASSWORD: password # In case a local postgres exists and env variable is already set.
      DB_POOL_SIZE:
      DB_PORT:
      DB_USE_SSL:
      DB_USERNAME: postgres # In case a local postgres exists and env variable is already set.
      FRONTEND_URL:
      HTTP_LOG_LEVEL: debug
      IDP_ENTITY_ID:
      JWT_SECRET:
      KOMPASSI_API_KEY:
      KOMPASSI_API_URL:
      NODE_ENV:
      SC_SECRET:
      SP_ASSERT_ENDPOINT:
      SP_ENTITY_ID:
      SP_PKEY:
      SSO_LOGIN_URL:
      SSO_LOGOUT_URL:
      TELIA_BATCH_ENDPOINT:
      TELIA_ENDPOINT:
      TELIA_PASSWORD:
      TELIA_USER:
      TELIA_USERNAME:
      USE_DETAILED_LOGS: true
      USE_JSON_LOGS:
    command: sh -c "npm i && npm run dev"

  frontend:
    image: node:24.15-alpine
    working_dir: /frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      VITE_API_TARGET_HOST: backend
      VITE_DEV_SERVER_PORT: 3001
      VITE_USE_ALT_ERR_MSG:
    command: sh -c "npm i && npm run dev"

  admin-frontend:
    image: node:24.15-alpine
    working_dir: /admin-frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - 3002:3000
    volumes:
      - ./admin-frontend:/admin-frontend
      - /admin-frontend/node_modules
    environment:
      VITE_API_TARGET_HOST: backend
      VITE_DEV_SERVER_PORT: 3002
      VITE_ENABLE_EXTRA_ENTRIES: true
      VITE_ENABLE_KOMPASSI_INTEGRATION: true
      VITE_ENTRA_CLIENT_ID:
      VITE_ENTRA_REDIRECT_URI: http://localhost:3002/loginEntraID
      VITE_ENTRA_TENANT_ID:
    command: sh -c "npm i && npm run dev"

  db:
    image: postgres:18
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nuta
