services:
    db:
      image: postgres:11
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: nuta
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      expose:
        - 5432

    app:
      image: mobiilinutakortti_backend
      depends_on:
        - db
      ports:
        - 3000:3000
volumes:
  db-data:
